package org.issn.issnbot.doc;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.apache.commons.io.FileUtils;
import org.issn.issnbot.WikidataSerial;

public class AlgorithmDocumentationGenerator {

	public static void main(String[] args) throws IOException {
		File outputFile = new File(args[0]);
		StringBuffer sb = new StringBuffer();
		sb.append("# ISSNBot update algorithm"+"\n");
		sb.append("_note : this file is automatically generated from the documentation in `WikidataSerial.java`._"+"\n");
		sb.append("\n");
		sb.append("This is the algorithms ISSNBot uses to update Wikidata. They are applied in the order listed here."+"\n");
		sb.append("\n");
		
		Method[] methods = WikidataSerial.class.getMethods();
		List<Description> descriptions = new ArrayList<>();
		for (Method m : methods) {
			Description d = m.getAnnotation(Description.class);
			if(d != null) {
				descriptions.add(d);
			}
		}
		
		// sort based on order
		Collections.sort(descriptions, (d1, d2) -> d1.order() - d2.order());
		
		for (Description description : descriptions) {
			sb.append("## "+description.title()+"\n");
			sb.append("\n");
			sb.append(description.definition()+"\n");
			sb.append("\n");
		}

		FileUtils.write(outputFile, sb.toString(), "UTF-8");
	}
	
}
