package org.issn.issnbot.doc;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.issn.issnbot.WikidataUpdateStatus;

public class UpdateStatusDocumentationGenerator {

	public static void main(String[] args) throws IOException {
		File outputFile = new File(args[0]);
		StringBuffer sb = new StringBuffer();
		sb.append("# Wikidata Update Statuses"+"\n");
		sb.append("_note : this file is automatically generated from the source code._"+"\n");
		sb.append("\n");
		sb.append("This is the list of possible statuses that the ISSNbot returns in its output log file."+"\n");
		sb.append("\n");
		
		for (WikidataUpdateStatus aStatus : WikidataUpdateStatus.values()) {			
			try {
				Description d = aStatus.getClass().getField(aStatus.name()).getAnnotation(Description.class);
				if(d != null) {
					sb.append("## "+aStatus.name()+"\n");
					sb.append("  - definition : "+d.definition()+"\n");
					sb.append("  - order/code : "+aStatus.getOrder()+"\n");
					sb.append("\n");
				}
			} catch (Exception e) {
				e.printStackTrace();
			}			
		}
		FileUtils.write(outputFile, sb.toString(), "UTF-8");
	}
	
}
